// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhtwrxhorlzwjynwxxny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpodHdyeGhvcmx6d2p5bnd4eG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mzg0NTgsImV4cCI6MjA3MzUxNDQ1OH0.rN4nesx4RqU20XuY0xqvv5oy_kV4IDVRcLCQ--Lf9vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});